export declare type DicomElements = {
  PatientName: string; // 患者姓名
  PatientID: string; // 患者ID
  OtherPatientIDs: string; // 患者其他ID
  IssuerOfPatientID: 'SYSTEM' | string; // 患者ID生成方式
  PatientBirthDate: string; // 患者生日
  PatientSex: string; // 患者性别
  PatientAge: string; // 患者年龄
  AccessionNumber: string; // 检查号
  AcquisitionDateTime: string; // 采集时间，worklist信息获取时间
  StudyDate: string; // 检查日期
  StudyTime: string; // 检查时间
  InstanceCreationDate: string; // 实例创建日期
  InstanceCreationTime: string; // 实例创建时间
  AcquisitionDate: string; // 图像生成日期
  ContentDate: string; // 内容生成日期
  AcquisitionTime: string; // 图像生成时间
  ContentTime: string; // 内容生成日期
  StudyDescription: string; // 检查描述
  SeriesDescription: string; // 序列描述,
  SpecificCharacterSet: string; // 特定字符集，
  ImageType: string[]; // 图像类型
  SOPClassUID: string; // SOP类型UID
  SOPInstanceUID: string; // SOP实例UID
  Modality: string; // 设备
  ModalitiesInStudy: string; // 图像模式
  Manufacturer: string; // 设备厂家
  ManufacturerModelName: string; // 设备型号
  InstitutionName: string; // 医院名称
  InstitutionAddress: string; // 医院地址
  ReferringPhysicianName: string; // 转诊医生姓名
  StationName: string; // 工作站名称
  InstitutionalDepartmentName: string; // 科室
  OperatorsName: string; // 操作医生工号
  RequestedProcedureDescription: string; // 检查描述
  RequestedContrastAgent: string; // 造影剂
  PreMedication: string; // 用药方式
  ScheduledStationAETitle: string; // 计划执行的工作站AETitle
  ScheduledProcedureStepStartDate: string; // 计划程序开始日期
  ScheduledProcedureStepStartTime: string; // 计划程序开始时间
  ScheduledPerformingPhysiciansName: string; // 计划程序执行医生
  ScheduledProcedureStepDescription: string; // 计划程序执行描述
  ScheduledProcedureStepID: string; // 计划程序执行ID
  ScheduledStationName: string; // 计划执行的工作站名称
  ScheduledProcedureStepLocation: string; // 计划程序位置
  ReferencedPerformedProcedureStepSequence: unknown[]; // 参考执行的程序步骤序列
  ReferencedImageSequence: unknown[]; // 使用的图像序列
  IrradiationEventUID: string; // 辐射事件UID
  MedicalAlerts: string; // 医疗警报
  ScanOptions: string; // 扫描模式
  SliceThickness: number; // 切片厚度
  KVP: number; // KV值
  SpacingBetweenSlices: number; // 切片间距
  ReconstructionDiameter: number; // 重建直径
  DataCollectionDiameter: number; // 数据采集直径
  SoftwareVersions: string; // 软件版本
  ProtocolName: string; // 扫描协议
  GantryDetectorTilt: number; // 机架倾斜角度
  TableHeight: number; // 扫描床高度
  RotationDirection: string; // 球馆旋转方向
  ExposureTime: number; // 曝光时间
  XRayTubeCurrent: number; // X线管电流
  Exposure: number; // 曝光时间
  FilterType: string; // 图像过滤函数
  ConvolutionKernel: string; // 卷积核
  CTExposureSequence: unknown[]; // CT曝光顺序
  ExposureModulationType: string; // 曝光调制类型
  EstimatedDoseSaving: number; // 预计节省计量
  CTDIvol: number; // CT D卷
  StudyInstanceUID: string; // 检查实例UID
  SeriesInstanceUID: string; // 序列实例UID
  StudyID: string; // 设备检查ID
  SeriesNumber: number; // 序列号
  AcquisitionNumber: number; // 采集编号
  InstanceNumber: number; // 实例编号
  ImagePositionPatient: number[]; // 患者定位位置
  ImageOrientationPatient: number[]; // 图像定位患者
  FrameOfReferenceUID: string; // 参考架构UID
  Laterality: string; // 偏中心
  PositionReferenceIndicator: string; // 位置参考指示器
  SliceLocation: number; // 切片位置
  NumberOfStudyRelatedInstances: number; // 检查相关的实例的数量
  ImageComments: string; // 图像注释
  SamplesPerPixel: number; // 单个像素采样数
  PhotometricInterpretation: string; // 光度解析
  PlanarConfiguration: number; // 平面配置
  Rows: number; // 图像行数
  Columns: number; // 图像列数
  RETIRED_Planes: number; // 偏远平面
  PixelSpacing: [number, number]; // 像素间距
  PixelAspectRatio: [number, number]; // 像素纵横比
  BitsAllocated: number; // 图像位数
  BitsStored: number; // 存储位数
  HighBit: number; // 最高bit位
  PixelRepresentation: number; // 像素标识方法
  WindowCenter: number; // 窗中心
  WindowWidth: number; // 窗宽
  RescaleIntercept: number; // 重缩放截距
  RescaleSlope: number; // 重缩放坡度
  WindowCenterWidthExplanation: string; // 窗宽窗位说明
  PerformedProcedureStepID: string; // 执行的过程步骤ID
  RequestAttributesSequence: unknown; // 请求的序列属性
  IconImageSequence: unknown; // 图标图像序列
  PixelData: ArrayBuffer[]; // 图像数据
}

export declare type DicomElements_WML = {
  PatientName: string; // 患者姓名
  PatientID: string; // 患者ID
  OtherPatientIDs: string; // 患者其他ID
  IssuerOfPatientID: 'SYSTEM' | string; // 患者ID生成方式
  PatientBirthDate: string; // 患者生日
  PatientSex: string; // 患者性别
  PatientAge: string; // 患者年龄
  AccessionNumber: string; // 检查号
  AcquisitionDateTime: string; // 采集时间，worklist信息获取时间
  StudyDate: string; // 检查日期
  StudyTime: string; // 检查时间
  InstanceCreationDate: string; // 实例创建日期
  InstanceCreationTime: string; // 实例创建时间
  AcquisitionDate: string; // 图像生成日期
  ContentDate: string; // 内容生成日期
  AcquisitionTime: string; // 图像生成时间
  ContentTime: string; // 内容生成日期
  StudyDescription: string; // 检查描述
  SeriesDescription: string; // 序列描述
  ReferringPhysicianName: string; // 转诊医生姓名
  StationName: string; // 工作站名称
  InstitutionalDepartmentName: string; // 科室
  OperatorsName: string; // 操作医生工号
  RequestedProcedureDescription: string; // 检查描述
  RequestedContrastAgent: string; // 造影剂
  PreMedication: string; // 用药方式
  SpecificCharacterSet: string; // 特定字符集，
  ImageType: string[]; // 图像类型
  Modality: string; // 设备
  InstitutionName: string; // 医院名称
  InstitutionAddress: string; // 医院地址
}

